name: Notify Discord on Push

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  discordNotify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$(jq -n --arg repo "${{ github.repository }}" \
                            --arg branch "${{ github.ref_name }}" \
                            --arg commit "${{ github.event.head_commit.message }}" \
                            --arg url "${{ github.event.head_commit.url }}" \
                            '{"username": "GitHub", "content": "**New Push to Repository!**\nRepo: \($repo)\nBranch: \($branch)\nCommit: \($commit)\n[View Commit](\($url))"}')" \
               "$DISCORD_WEBHOOK_URL"
