name: Notify Discord on Push

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  discordNotify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$(jq -n --arg repo "${{ github.repository }}" \
                            --arg branch "${{ github.ref_name }}" \
                            --arg commit "${{ github.event.head_commit.message }}" \
                            --arg url "${{ github.event.head_commit.url }}" \
                            --argjson color 8388736 \
                            '{
                              "username": "GitHub",
                              "embeds": [{
                                "title": "🚀 New Push to Repository!",
                                "color": $color,
                                "fields": [
                                  { "name": "Repository", "value": "`\($repo)`", "inline": true },
                                  { "name": "Branch", "value": "`\($branch)`", "inline": true },
                                  { "name": "Commit Message", "value": "\($commit)", "inline": false }
                                ],
                                "url": "\($url)",
                                "footer": { "text": "GitHub Actions • Push Notification" }
                              }]
                            }')" \
               "$DISCORD_WEBHOOK_URL"
